Add GH username, and repo to form. Update pipeline script

diff --git a/.bluemix/pipeline.yml b/.bluemix/pipeline.yml
--- a/.bluemix/pipeline.yml
+++ b/.bluemix/pipeline.yml
@@ -26,12 +26,33 @@ stages:
     curratedDockerImage: default
     script: |
       #!/bin/bash
+      function createPR () {
+        if [ -z $GH_API_KEY ]
+        then
+          branch_name="$(date +%Y%m%d.%H%M%S)"
+          user_name=$GH_USERNAME
+          token=$GH_API_KEY
+          repo=$GH_REPO
+          git checkout -b pr/${branch_name}
+          git add .
+          git commit -m "${branch_name}"
+          git push -u https://${user_name}:${token}@github.com/${repo}.git
+          curl -X POST -H "Content-Type: application/json" -d \
+          '{"title":"'"$branch_name"'", "body":"'"$branch_name"'", "head":"'"pr/$branch_name"'", "base":"master"}' \
+          https://${user_name}:${token}@api.github.com/repos/${repo}/pulls
+        fi
+      }
 
       echo "Running tests"
       ${TEST_COMMAND}
-      # TODO: if command successful, create PR using Dan's stuff, create ticket on github
+      if test $? -eq 0 
+      then
+        createPR
+      else
+        echo "Tests failed"
+      fi
     test_type: simple
-  - name: FaaS Deploy
+  - name: Deploy to stage
     type: deployer
     target:
       region_id: ${PROD_REGION_ID}
